services:
  gateway:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.ignition-mes.entrypoints: "web"
      traefik.http.routers.ignition-mes.rule: "Host(`ignition-mes.localtest.me`)"
      traefik.http.services.ignition-mes.loadbalancer.server.port: "8088"
    environment:
      GATEWAY_SYSTEM_NAME: ignition-mes
      GATEWAY_PUBLIC_HTTP_PORT: 80
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: ignition-mes.localtest.me
    networks:
      - default
      - proxy
  
  database:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.mssql-database-template.entrypoints: "web"
      traefik.http.routers.mssql-database-template.rule: "Host(`mssql-database-template.localtest.me`)"
      traefik.http.services.mssql-database-template.loadbalancer.server.port: "1433"
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy